### ISSUE TITLE
notebook 2 identifier comment

### ISSUE THREAD

**Issue by danielskatz** [yorkiva/FAIR-Exercises#8]
You write

F1. (Meta)data are assigned a globally unique and persistent identifier

The identifier associated with the MNIST dataset is essentially the URL of the hosting web server: http://yann.lecun.com/exdb/mnist/. This is clerly unique but not necessarily persistent as webpages are prone to deprecation when domain names are lost or restructured.

Assessment of uniqueness: Pass 
Assessment of persistence: Fail

but the data could be changed, so I don't think the data have been assigned a unique identifier.

Note that any place where "(Meta)data" is written in the principles is shorthand, and this can be expanded to both "Metadata are assigned a globally unique and persistent identifier" and "Data are assigned a globally unique and persistent identifier"

**Comment by danielskatz** [comment]
Note that the first part of this issue is one that is better handled in the equivalent part of notebook 3:

>The identifier associated with the CDMS dataset is essentially the URL of the hosting git repo: https://github.com/FAIR-UMN/FAIR-UMN-CDMS/blob/main/data/processed_csv/processed_combined.csv. This is neither unique nor persistent since (1) content of git repositories can be changed as the user keeps modifying it and (2) github repos are not permanent URIs.

**Comment by yorkiva** [comment]
I have modified the FAIRness assessment of MNIST, with more details on F1 evaluation criterion. I changed the assessment of uniqueness to partially pass, since data and metadata share the same identifier.
